### ISSUE TITLE
Create installer for Windows

### ISSUE THREAD

**Issue by cdupuis** [atomist/rug-cli#6]

**Comment by Lawouach** [comment]
Some updates here.

We made the decision to use Chocolatey to package up and distribute the CLI. That seems to have become a fairly standard mechanism in Windows land.

Chocolatey packages are Nuget packages with a twist. So, their format is close to what the [official Nuget spec defines](https://docs.nuget.org/ndocs/schema/nuspec). Essentially, a package is made of:

* a nuget spec (XML manifest)
* a directory of powershell scripts that are executed at install/uninstall times
* a couple of chocolatey metadata files (XML mostly)

Usually, you'd use the chocolatey command line to create, package and publish your package. But, this is a .NET app and would require us to grab mono in our travis build, slowing it down massively.

Instead, since the package is actually a zip, we'll try to simply update the manifests, then zip the package and push it again.

For now, the difficulty is finding the right HTTP call to publish without the chocolatey command.

**Comment by Lawouach** [comment]
The package now upload to our Nuget feed through a simple curl command.

The installation steps are also documented. 

Need some more testing before completing this story.

**Comment by Lawouach** [comment]
Installer works as expected and documentation can be found at https://github.com/atomist/rug-cli/blob/master/docs/install-windows.md
