### ISSUE TITLE
CLI does not apply Rug parameter regex parameter checking on default parameter values

### ISSUE THREAD

**Issue by russmiles** [atomist/rug-cli#63]
It seems to be possible to supply a default parameter value on a generator that does not meet the requirements of the parameters regex parameter.

**Comment by cdupuis** [comment]
How do you specify a default value for a parameter on the CLI? Are you talking about the `--interactive`

**Comment by ddgenome** [comment]
He means if you do not specify a value for a parameter that is optional and has a default value, the default value provided in the editor/generator is not validated against the parameter's regex. I would guess this is an issue in Rug, not the CLI, although it might be better to address when packaging an archive than when running it. Although you may have to do both to catch local changes when using `-l`.

This represents a difference in behavior of the CLI and buttons, not sure about the bot. Since the button forms do real-time validation, the leaving an invalid, provided default value will not allow submission.

**Comment by cdupuis** [comment]
@ddgenome thanks. This is a Rug issue as the CLI uses Rug to validate parameters. We should move that over.

**Comment by ddgenome** [comment]
Moved to atomist/rug#168
